common_packages:
  - git
  - curl
  - wget
  - vim
  - rsync
  - tar
  - unzip
  - htop
  - iftop
  - nload
  - bmon
  - btop
  - tmux
  - jq
  - tree
  - mpich
  - mpich-devel

enable_chrony: true

# =====================
# SSH (password habilitado)
# =====================
ssh_port: 22
ssh_permit_root_login: "yes"
ssh_password_authentication: "yes"

# =====================
# LLM env (micromamba)
# =====================
llm_conda_packages:
  - python
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - numba
  - cudatoolkit
  - transformers
  - datasets
  - accelerate
  - peft
  - safetensors
  - sentencepiece


llm_pip_packages:
  - transformers
  - datasets
  - accelerate
  - peft
  - safetensors
  - sentencepiece

llm_python_packages:
  - numpy
  - torch
  - transformers

# =====================
# Variables operacionales del cluster
# =====================
#
# Slurm (topologia, puertos, particiones), red interna HPC y firewall viven en:
# - group_vars/all/vars.yml
