common_packages:
  - git
  - curl
  - wget
  - vim
  - rsync
  - tar
  - unzip
  - htop
  - tmux
  - jq

enable_chrony: true

# =====================
# SSH (password habilitado)
# =====================
ssh_port: 22
ssh_permit_root_login: "yes"
ssh_password_authentication: "yes"

llm_python_packages:
  - numpy
  - torch
  - transformers
