# Export NFS del proyecto LLM (master)
nfs_exports:
  - path: "{{ llm_nfs_export_dir }}"
    clients: "{{ llm_internal_cidr }}(rw,sync,no_subtree_check,root_squash)"

# MariaDB module stream (Rocky/RHEL)
mariadb_module_stream: "10.11"
