---
validate_nfs: true
validate_cuda: true
validate_llm: true

validate_nfs_mount_path: "{{ llm_nfs_mount_dir | default('/mnt/llm-project') }}"
validate_nfs_export_path: "{{ llm_nfs_export_dir | default('/export/llm-project') }}"

llm_micromamba_root: "/opt/micromamba"
llm_micromamba_bin: "/opt/micromamba/bin/micromamba"
llm_env_name: "llm"
