---
- name: Baseline para todos los nodos (SO + SSH + Firewall + GPU/CUDA + Entorno LLM)
  hosts: all
  become: true
  gather_facts: true
  roles:
    - { role: common, tags: ["common"] }
    - { role: users_ssh, tags: ["ssh"] }
    - { role: firewall, tags: ["firewall"] }
    - { role: network_internal, tags: ["network_internal"] }
    - { role: nvidia_cuda, tags: ["cuda"] }
    - { role: llm_env, tags: ["llm"] }

- name: Configuración NFS en master
  hosts: hpc_master
  become: true
  gather_facts: true
  roles:
    - { role: nfs_server, tags: ["nfs"] }
    - { role: llm_project, tags: ["llm_project"] }

- name: MariaDB en master
  hosts: hpc_master
  become: true
  gather_facts: true
  roles:
    - { role: mariadb_server, tags: ["mariadb"] }

- name: Preparar SlurmDB en MariaDB (master)
  hosts: hpc_master
  become: true
  gather_facts: true
  roles:
    - { role: slurm_db_prep, tags: ["mariadb", "slurmdb"] }

- name: Configuración NFS en workers
  hosts: workers
  become: true
  gather_facts: true
  roles:
    - { role: nfs_client, tags: ["nfs"] }

- name: Validación de salud del clúster
  hosts: all
  become: true
  gather_facts: true
  roles:
    - { role: validate, tags: ["validate"] }

- name: Configuración de identidades SLURM
  hosts: all
  become: true
  roles:
    - role: slurm_identities
      tags: [slurm, munge, identities]

- name: Configuración de munge en nodos SLURM
  hosts: all
  become: true
  roles:
    - role: munge
      tags: [munge]

- name: Recopilación de hechos SLURM en todos los nodos
  hosts: all
  become: true
  roles:
    - role: slurm_facts
      tags: [slurm, slurm_facts]

- name: Configuración de SLURM en nodo master
  hosts: hpc_master
  become: true
  roles:
    - role: slurm_rpm_build
    - role: slurm_install
      tags: [slurm, slurm_install]
    - { role: slurm_controller, tags: ["slurm", "slurm_config"] }

- name: Configuración de SLURM en nodos workers
  hosts: workers
  become: true
  roles:
    - role: slurm_compute
      tags: [slurm, slurm_config]
