---
network_internal_keep_if: "eno1"
network_internal_exclude_ifaces:
  - "tailscale0"
network_internal_exclude_conn_regex: ".*tailscale.*"

network_internal_links:
  worker1:
    master_if: "enp3s0f1"
    master_ip: "192.168.34.1/28"
    worker_if: "enp3s0f1"
    worker_ip: "192.168.34.2/28"
  worker2:
    master_if: "enp3s0f2"
    master_ip: "192.168.34.17/28"
    worker_if: "enp3s0f2"
    worker_ip: "192.168.34.18/28"
  worker3:
    master_if: "enp3s0f3"
    master_ip: "192.168.34.33/28"
    worker_if: "enp3s0f3"
    worker_ip: "192.168.34.34/28"
  worker4:
    master_if: "enp3s0f0"
    master_ip: "192.168.34.49/28"
    worker_if: "enp3s0f0"
    worker_ip: "192.168.34.50/28"
