# Limites visibles para Slurm en worker1 (reserva para administracion).
# Ajusta estos valores cuando necesites reservar recursos del nodo.
slurm_cpus: 16
slurm_sockets: 1
slurm_cores_per_socket: 8
slurm_threads_per_core: 2
slurm_real_memory: 56000
slurm_node_gres: "gpu:quadro_p1000:1"
