---
- name: NFS Client | Install packages
  ansible.builtin.dnf:
    name:
      - nfs-utils
    state: present
    update_cache: true

- name: NFS Client | Ensure mount points exist
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: "0775"
  loop: "{{ nfs_mounts }}"

- name: NFS Client | Ensure NFS mounts present and mounted
  ansible.builtin.mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    state: mounted
  loop: "{{ nfs_mounts }}"
